name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: 'Login to npmjs npm repo .npmrc'
        shell: bash
        run: |
          echo "@imaginelearning:registry=https://npm.pkg.github.com/ImagineLearning" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{secrets.PACKAGE_AUTH_TOKEN}}" >> .npmrc
          echo "always-auth = true" >> .npmrc
      - run: yarn install
      - run: yarn tsc
      - run: yarn publish